/**
 * Privacy screen — explains local vs online mode, approved roots,
 * and provides clear local draft/cache controls.
 * Per react-native-ui-ux-plan.md §4G (Privacy) and §8 safety rules 3, 5.
 */
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, spacing, fontSize, borderRadius, shadow } from '@/theme/tokens';
import { Shield, Database, Trash2, Download, Check } from 'lucide-react-native';
import { useBackendHealth } from '@/features/assistant/connectionService';

export default function PrivacyScreen() {
  const { health, isOnline } = useBackendHealth(true);

  const provider = health?.chat_provider || 'None';
  const isLocalOnly = provider === null || provider === 'None';
  const chunks = typeof health?.indexed_chunks === 'number' ? health.indexed_chunks : '?';
  const roots = Array.isArray(health?.registered_roots) ? health.registered_roots.length : '?';

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <ScrollView>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Privacy mode</Text>
          <View style={styles.card}>
            <View style={styles.privacyRow}>
              <Shield color={isLocalOnly ? colors.local : colors.online} size={20} strokeWidth={1.5} />
              <View>
                <Text style={styles.privacyLabel}>
                  {isLocalOnly ? 'Local by default' : 'Online mode active'}
                </Text>
                <Text style={styles.privacyDesc}>
                  {isLocalOnly
                    ? 'All responses come from your local index (FTS5 RAG). No cloud API keys are used.'
                    : `Responses may be generated by ${provider}, which may send data off-device.`}
                </Text>
              </View>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Local data</Text>
          <View style={styles.card}>
            <PrivacyInfoRow icon={<Database />} label="Indexed chunks" value={chunks} />
            <PrivacyInfoRow icon={<Database />} label="Approved roots" value={roots} />
            <PrivacyInfoRow
              icon={<Download />}
              label="Chat history"
              value="Opt-in per request"
              desc="History is stored locally and never synced."
            />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Local storage</Text>
          <View style={styles.card}>
            <TouchableOpacity
              style={styles.storageRow}
              onPress={() => {}}
              accessible
              accessibilityRole="button"
              accessibilityLabel="Clear local drafts"
            >
              <View style={styles.storageLeft}>
                <Trash2 color={colors.danger} size={20} strokeWidth={1.5} />
                <Text style={styles.storageLabel}>Clear drafts and cache</Text>
              </View>
              <Text style={styles.storageAction}>Clear</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.storageRow, styles.storageRowLast]}
              onPress={() => {}}
              accessible
              accessibilityRole="button"
              accessibilityLabel="Export diagnostics"
            >
              <View style={styles.storageLeft}>
                <Download color={colors.accent} size={20} strokeWidth={1.5} />
                <Text style={styles.storageLabel}>Export diagnostics</Text>
              </View>
              <Text style={styles.storageAction}>Export</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

function PrivacyInfoRow({
  icon,
  label,
  value,
  desc,
}: {
  icon: React.ReactNode;
  label: string;
  value: string | number;
  desc?: string;
}) {
  return (
    <View style={styles.infoRow}>
      <View style={styles.infoLeft}>
        {icon}
        <Text style={styles.infoLabel}>{label}</Text>
      </View>
      <View style={styles.infoRight}>
        <Text style={styles.infoValue}>{value}</Text>
        {desc && <Text style={styles.infoDesc}>{desc}</Text>}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  section: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  sectionTitle: {
    fontSize: fontSize.xs,
    fontWeight: '600',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: spacing.xs,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    ...shadow.sm,
  },
  privacyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
  },
  privacyLabel: {
    fontSize: fontSize.lg,
    fontWeight: '600',
    color: colors.text,
  },
  privacyDesc: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    marginTop: 2,
    lineHeight: 18,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  infoLabel: {
    fontSize: fontSize.base,
    color: colors.text,
  },
  infoRight: {
    alignItems: 'flex-end',
  },
  infoValue: {
    fontSize: fontSize.base,
    fontWeight: '600',
    color: colors.text,
  },
  infoDesc: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginTop: 2,
  },
  storageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  storageRowLast: {
    borderBottomWidth: 0,
  },
  storageLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  storageLabel: {
    fontSize: fontSize.base,
    color: colors.text,
  },
  storageAction: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: colors.accent,
  },
});
